export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const NEWUSER_FAILURE = 'NEWUSER_FAILURE';
export const NEWUSER_REQUEST = 'NEWUSER_REQUST';
export const NEWUSER_SUCCESS = 'NEWUSER_SUCCESS';
