export const MIRROR_GET_FAILURE = 'MIRROR_GET_FAILURE';
export const MIRROR_GET_REQUEST = 'MIRROR_GET_REQUEST';
export const MIRROR_GET_SUCCESS = 'MIRROR_GET_SUCCESS';

export const MIRROR_POST_FAILURE = 'MIRROR_POST_FAILURE';
export const MIRROR_POST_REQUEST = 'MIRROR_POST_REQUEST';
export const MIRROR_POST_SUCCESS = 'MIRROR_POST_SUCCESS';

export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
