// Mirror

export const MIRROR_GET_FAILURE = 'MIRROR_GET_FAILURE';
export const MIRROR_GET_REQUEST = 'MIRROR_GET_REQUEST';
export const MIRROR_GET_SUCCESS = 'MIRROR_GET_SUCCESS';

export const MIRROR_POST_FAILURE = 'MIRROR_POST_FAILURE';
export const MIRROR_POST_REQUEST = 'MIRROR_POST_REQUEST';
export const MIRROR_POST_SUCCESS = 'MIRROR_POST_SUCCESS';

export const MIRROR_DELETE_REQUEST = 'MIRROR_DELETE_REQUEST';
export const MIRROR_DELETE_SUCCESS = 'MIRROR_DELETE_SUCCESS';
export const MIRROR_DELETE_FAILURE = 'MIRROR_DELETE_FAILURE';

export const CURRENT_MIRROR = 'CURRENT_MIRROR';
// Section

export const SECTION_POST_FAILURE = 'SECTION_POST_FAILURE';
export const SECTION_POST_REQUEST = 'SECTION_POST_REQUEST';
export const SECTION_POST_SUCCESS = 'SECTION_POST_SUCCESS';

export const SECTION_DELETE_REQUEST = 'SECTION_DELETE_REQUEST';
export const SECTION_DELETE_SUCCESS = 'SECTION_DELETE_SUCCESS';
export const SECTION_DELETE_FAILURE = 'SECTION_DELETE_FAILURE';

// Weather

export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";

export const UPDATE_WEATHER = "UPDATE_WEATHER";

// Option

export const OPTION_DELETE_REQUEST = 'OPTION_DELETE_REQUEST';
export const OPTION_DELETE_SUCCESS = 'OPTION_DELETE_SUCCESS';
export const OPTION_DELETE_FAILURE = 'OPTION_DELETE_FAILURE';
